export interface BlogPost {
  slug: string;
  title: string;
  description: string;
  date: string;
  author: string;
  category: string;
  readTime: string;
  image: string;
  content: string[];
}

export const blogPosts: BlogPost[] = [
  {
    slug: "manfaat-daily-report-untuk-perkembangan-anak-paud",
    title: "Manfaat Daily Report untuk Perkembangan Anak PAUD",
    description: "Daily report membantu orang tua memantau aktivitas harian anak di sekolah. Simak manfaat lengkapnya untuk tumbuh kembang si kecil di artikel ini.",
    date: "2026-07-28",
    author: "Tim CDPS",
    category: "Tips Parenting",
    readTime: "5 menit",
    image: "/blog/placeholder.svg",
    content: [
      "Daily report adalah salah satu fitur paling penting dalam sistem informasi manajemen sekolah PAUD dan TK. Laporan harian ini mencatat seluruh aktivitas anak selama di sekolah — mulai dari kegiatan belajar, waktu makan, istirahat, hingga interaksi sosial dengan teman-temannya. Bagi orang tua yang bekerja, daily report menjadi jendela untuk tetap terhubung dengan perkembangan anak meskipun tidak bisa mendampingi langsung.",
      "## Apa Itu Daily Report untuk Anak PAUD?",
      "Daily report atau laporan harian adalah catatan sistematis yang dibuat oleh guru setiap hari untuk mendokumentasikan aktivitas dan perkembangan anak. Dalam konteks pendidikan anak usia dini, daily report mencakup aspek-aspek penting seperti kegiatan belajar, kondisi kesehatan, pola makan, waktu tidur, dan pencapaian harian anak.",
      "Dulu, daily report ditulis manual di buku penghubung yang harus dibawa pulang anak setiap hari. Sayangnya, buku sering tertinggal, basah kena hujan, atau tulisan guru sulit terbaca. Kini, dengan daily report digital dari CDPS, semua kendala itu teratasi.",
      "## Manfaat Daily Report Digital untuk Orang Tua",
      "### 1. Pantau Perkembangan Anak Secara Real-Time",
      "Orang tua bisa langsung mendapat notifikasi setiap kali guru memperbarui laporan harian. Tidak perlu menunggu rapat akhir semester atau bertanya-tanya apa yang dilakukan anak di sekolah. Cukup buka smartphone, semua informasi tersedia.",
      "### 2. Deteksi Dini Gangguan Perkembangan",
      "Dengan data harian yang tercatat rapi, orang tua dan guru dapat melihat pola perkembangan anak. Misalnya, jika anak tiba-tiba malas makan atau menarik diri dari teman-temannya, ini bisa segera ditindaklanjuti sebelum menjadi masalah yang lebih serius.",
      "### 3. Memperkuat Komunikasi Guru dan Orang Tua",
      "Daily report menjadi jembatan komunikasi yang efektif antara guru dan orang tua. Guru bisa menyampaikan informasi penting, orang tua bisa memberikan catatan atau pertanyaan. Semua tercatat rapi tanpa harus saling kejar-kejaran di grup WhatsApp.",
      "## Manfaat Daily Report Digital untuk Guru dan Sekolah",
      "Bagi guru, daily report digital otomatis mendokumentasikan pencapaian setiap anak secara sistematis. Data ini sangat berguna saat guru menyusun laporan perkembangan bulanan atau laporan triwulan. Guru tidak perlu lagi merekapl ulang dari buku catatan yang berserakan.",
      "Bagi sekolah, penggunaan daily report digital meningkatkan kredibilitas dan profesionalisme. Orang tua akan lebih percaya pada sekolah yang memiliki sistem pelaporan harian yang transparan dan terstruktur.",
      "## Mengapa Memilih CDPS untuk Daily Report?",
      "CDPS (Child Development Portal System) dirancang khusus untuk kebutuhan sekolah PAUD dan TK. Fitur daily report di CDPS dilengkapi dengan template yang bisa disesuaikan dengan kurikulum masing-masing sekolah. Guru cukup mengisi form, dan laporan otomatis terkirim ke orang tua.",
      "Semua data tersimpan aman di cloud dengan enkripsi. Orang tua hanya bisa melihat laporan anaknya sendiri, sementara sekolah memiliki akses penuh untuk kepentingan evaluasi. Dengan CDPS, daily report bukan lagi sekadar catatan kertas — tetapi alat bantu tumbuh kembang anak yang sesungguhnya.",
    ],
  },
  {
    slug: "cara-memilih-sekolah-paud-yang-tepat",
    title: "Cara Memilih Sekolah PAUD yang Tepat untuk Si Kecil",
    description: "Bingung memilih PAUD untuk anak? Simak panduan lengkap cara memilih sekolah PAUD yang sesuai dengan kebutuhan dan tumbuh kembang buah hati Anda.",
    date: "2026-07-25",
    author: "Tim CDPS",
    category: "Panduan",
    readTime: "6 menit",
    image: "/blog/placeholder.svg",
    content: [
      "Memilih sekolah PAUD adalah salah satu keputusan paling penting bagi setiap orang tua. Pendidikan anak usia dini menjadi fondasi yang akan memengaruhi tumbuh kembang anak di masa depan. Namun, dengan banyaknya pilihan sekolah PAUD saat ini, bagaimana cara memilih yang paling tepat? Artikel ini akan membantu Anda menemukan jawabannya.",
      "## Mengapa Memilih PAUD yang Tepat Itu Penting?",
      "Tiga tahun pertama kehidupan anak adalah periode emas (golden age) di mana otak anak berkembang paling pesat. Lingkungan belajar yang tepat akan membantu anak mengembangkan kemampuan kognitif, sosial-emosional, dan motorik secara optimal. Sebaliknya, lingkungan yang kurang mendukung bisa menghambat potensi anak.",
      "## 5 Cara Memilih Sekolah PAUD yang Tepat",
      "### 1. Perhatikan Kurikulum dan Metode Pembelajaran",
      "Setiap PAUD memiliki pendekatan berbeda. Ada yang menggunakan metode montessori yang menekankan kemandirian, metode sentra yang fokus pada area bermain, atau metode tematik yang mengintegrasikan berbagai mata pelajaran dalam satu tema. Pilih metode yang sesuai dengan gaya belajar dan kepribadian anak Anda.",
      "Kunjungi sesi trial atau open house untuk melihat langsung bagaimana guru mengajar dan bagaimana anak-anak berinteraksi. Metode pembelajaran yang baik bukan hanya mengajarkan calistung (membaca, menulis, berhitung), tetapi juga melatih keterampilan sosial, kemandirian, dan kreativitas.",
      "### 2. Cek Fasilitas dan Lingkungan Sekolah",
      "Lingkungan yang aman, bersih, dan nyaman adalah syarat mutlak. Perhatikan area bermain — apakah ada taman atau halaman untuk anak berlari? Apakah toilet bersih dan sesuai ukuran anak? Apalah ruang kelas memiliki ventilasi dan pencahayaan yang cukup? Keamanan juga penting: pastikan sekolah memiliki pagar yang kokoh, akses terbatas, dan prosedur penjemputan anak yang jelas.",
      "### 3. Kenali Kualifikasi Guru",
      "Guru PAUD harus memiliki kompetensi di bidang pendidikan anak usia dini. Idealnya, guru memiliki latar belakang pendidikan PAUD atau psikologi anak. Selain kualifikasi akademik, perhatikan juga sikap guru: apakah sabar, ramah, dan mampu berkomunikasi dengan baik dengan anak-anak. Rasio ideal guru dan murid adalah 1:8 agar perhatian bisa merata.",
      "### 4. Tanyakan Sistem Komunikasi dengan Orang Tua",
      "Sekolah PAUD yang baik memiliki sistem komunikasi yang transparan dengan orang tua. Apakah mereka menyediakan daily report? Apakah ada aplikasi atau portal khusus untuk memantau perkembangan anak? Sekolah yang menggunakan sistem digital seperti CDPS menunjukkan komitmen terhadap keterbukaan dan kemudahan akses informasi bagi orang tua.",
      "### 5. Libatkan Anak dalam Keputusan",
      "Ajak si kecil berkunjung ke sekolah. Perhatikan reaksinya — apakah ia terlihat antusias atau justru takut? Biarkan ia bermain sejenak di area bermain sambil Anda mengamati interaksinya dengan guru dan teman-teman. Anak yang nyaman dengan lingkungan sekolah akan lebih semangat belajar setiap hari.",
      "## Kesimpulan",
      "Memilih sekolah PAUD memang membutuhkan riset dan kunjungan langsung. Jangan terburu-buru dan jangan hanya tergiur dengan bangunan megah atau promosi. Prioritaskan kualitas pendidik, metode pembelajaran, dan sistem komunikasi yang transparan. Dengan memilih PAUD yang tepat, Anda telah memberikan langkah awal yang baik untuk masa depan si kecil.",
    ],
  },
  {
    slug: "pentingnya-portofolio-digital-pendidikan-anak-usia-dini",
    title: "Pentingnya Portofolio Digital dalam Pendidikan Anak Usia Dini",
    description: "Portofolio digital membantu mendokumentasikan perjalanan tumbuh kembang anak secara rapi, aman, dan lengkap. Simak manfaat lengkapnya di sini.",
    date: "2026-07-22",
    author: "Tim CDPS",
    category: "Edukasi",
    readTime: "5 menit",
    image: "/blog/placeholder.svg",
    content: [
      "Setiap anak memiliki perjalanan tumbuh kembang yang unik, dan mendokumentasikannya adalah salah satu hal terbaik yang bisa dilakukan orang tua dan guru. Dulu, portofolio anak dikumpulkan dalam map atau binder — gambar, lembar kerja, sertifikat, semuanya ditumpuk dan rawan rusak atau hilang. Kini, portofolio digital hadir sebagai solusi modern untuk dokumentasi perkembangan anak usia dini.",
      "## Apa Itu Portofolio Digital?",
      "Portofolio digital adalah kumpulan dokumentasi perkembangan anak dalam format digital. Ini mencakup foto kegiatan, video momen berharga, hasil karya seni, hingga catatan perkembangan dari guru. Semua tersimpan rapi dan bisa diakses kapan saja melalui perangkat yang terhubung internet.",
      "Berbeda dengan portofolio fisik, portofolio digital tidak memerlukan ruang penyimpanan khusus, tidak mudah rusak, dan bisa dibagikan dengan mudah ke pihak terkait — misalnya saat anak pindah sekolah atau melanjutkan ke jenjang pendidikan berikutnya.",
      "## Manfaat Portofolio Digital untuk Tumbuh Kembang Anak",
      "### 1. Dokumentasi yang Lebih Lengkap dan Terstruktur",
      "Dengan portofolio digital, setiap pencapaian anak tercatat rapi per semester. Foto, video, dan catatan guru tersimpan dalam satu tempat. Orang tua bisa melihat perkembangan anak secara visual — dari coretan pertama hingga gambar yang lebih kompleks, dari merangkak hingga berlari.",
      "### 2. Memudahkan Evaluasi Perkembangan Anak",
      "Guru dan orang tua bisa dengan mudah melacak perkembangan anak dari waktu ke waktu. Apakah ada peningkatan keterampilan motorik? Bagaimana perkembangan bahasanya? Data yang terdokumentasi dengan baik membantu dalam pengambilan keputusan terkait stimulasi dan intervensi dini jika diperlukan.",
      "### 3. Meningkatkan Keterlibatan Orang Tua",
      "Orang tua yang sibuk tetap bisa mengikuti perkembangan anak melalui portofolio digital. Setiap kali guru mengupload foto atau catatan baru, orang tua bisa melihatnya langsung. Ini membuat orang tua merasa lebih terlibat dalam proses pendidikan anak meskipun tidak bisa hadir di sekolah setiap hari.",
      "## Mengapa CDPS Menjadi Pilihan Tepat untuk Portofolio Digital?",
      "CDPS menyediakan fitur portofolio digital yang dirancang khusus untuk sekolah PAUD dan TK. Proses upload cepat dan mudah — guru cukup memotret hasil karya anak, memberikan catatan singkat, dan semua tersimpan otomatis di portofolio masing-masing anak.",
      "Keamanan data menjadi prioritas utama CDPS. Semua data tersimpan di server terenkripsi dan hanya bisa diakses oleh pihak yang berwenang — sekolah, guru, dan orang tua terkait. Privasi data anak tetap terjaga sepenuhnya.",
      "## Kesimpulan",
      "Portofolio digital bukan sekadar pengganti map kertas. Ini adalah alat dokumentasi yang lebih baik, lebih aman, dan lebih bermanfaat untuk memantau tumbuh kembang anak. Dengan CDPS, sekolah dan orang tua bisa berkolaborasi untuk memberikan yang terbaik bagi masa depan anak Indonesia.",
    ],
  },
  {
    slug: "tips-komunikasi-efektif-guru-dan-orang-tua",
    title: "Tips Komunikasi Efektif Antara Guru dan Orang Tua",
    description: "Komunikasi guru dan orang tua yang baik sangat penting untuk mendukung tumbuh kembang anak. Simak tips praktisnya di artikel ini.",
    date: "2026-07-19",
    author: "Tim CDPS",
    category: "Tips Parenting",
    readTime: "4 menit",
    image: "/blog/placeholder.svg",
    content: [
      "Kerjasama antara guru dan orang tua adalah kunci keberhasilan pendidikan anak usia dini. Sayangnya, komunikasi yang efektif sering terhambat oleh kesibukan masing-masing. Guru sibuk mengajar, orang tua sibuk bekerja. Akibatnya, informasi penting tentang perkembangan anak sering terlewat atau tidak tersampaikan dengan baik.",
      "## Mengapa Komunikasi Guru dan Orang Tua Itu Penting?",
      "Anak menghabiskan sebagian besar waktunya di dua lingkungan: rumah dan sekolah. Tanpa komunikasi yang baik antara guru dan orang tua, akan ada kesenjangan informasi. Guru mungkin tidak tahu bahwa anak sedang kurang tidur atau memiliki masalah di rumah. Orang tua mungkin tidak tahu bahwa anak mengalami kesulitan belajar atau bersosialisasi di sekolah.",
      "Komunikasi yang terjalin dengan baik memungkinkan kedua pihak bekerja sama untuk memberikan dukungan yang konsisten bagi tumbuh kembang anak. Dengan kata lain, guru dan orang tua adalah tim — dan tim yang baik harus saling berkomunikasi.",
      "## 5 Tips Komunikasi Efektif Guru dan Orang Tua",
      "### 1. Gunakan Aplikasi Khusus untuk Memantau Perkembangan Anak",
      "Grup WhatsApp memang praktis, tetapi seringkali tidak efektif untuk komunikasi formal. Pesan penting tenggelam di antara chat yang tidak relevan. Solusinya, gunakan aplikasi khusus seperti CDPS yang dirancang untuk komunikasi sekolah dan orang tua. Semua laporan, pengumuman, dan pesan terpusat dalam satu platform yang rapi.",
      "### 2. Jadwalkan Pertemuan Rutin",
      "Pertemuan tatap muka antara guru dan orang tua sebaiknya dilakukan minimal sebulan sekali. Bicarakan perkembangan anak secara spesifik — bukan hanya nilai akademik, tetapi juga aspek sosial, emosional, dan fisik. Buat agenda pertemuan agar diskusi lebih terarah dan efektif.",
      "### 3. Berikan Informasi yang Seimbang",
      "Guru sebaiknya tidak hanya menghubungi orang tua saat ada masalah. Sampaikan juga kabar baik dan pencapaian anak. Begitu pula sebaliknya, orang tua jangan ragu berbagi informasi tentang kondisi anak di rumah yang mungkin relevan dengan kegiatan di sekolah.",
      "### 4. Gunakan Bahasa yang Mudah Dipahami",
      "Hindari istilah teknis yang mungkin tidak dimengerti orang tua. Sampaikan informasi dengan bahasa yang sederhana dan jelas. Jika perlu berikan contoh konkret agar orang tua lebih mudah memahami situasi yang dimaksud.",
      "### 5. Libatkan Orang Tua dalam Proses Pembelajaran",
      "Komunikasi yang baik bukan hanya menyampaikan informasi, tetapi juga melibatkan orang tua. Berikan aktivitas lanjutan yang bisa dilakukan di rumah. Minta masukan orang tua tentang perkembangan anak. Dengan begitu, orang tua merasa dihargai dan lebih termotivasi untuk berpartisipasi.",
      "## Bagaimana CDPS Membantu Komunikasi Guru dan Orang Tua?",
      "CDPS menyediakan fitur daily report dengan notifikasi otomatis yang memastikan setiap informasi tersampaikan tepat waktu. Guru bisa mengirim laporan, foto, dan pesan langsung ke orang tua melalui platform. Orang tua pun bisa merespons atau bertanya dengan mudah. Semua riwayat komunikasi tersimpan rapi dan bisa diakses kapan saja.",
      "Dengan CDPS, komunikasi guru dan orang tua menjadi lebih mudah, lebih terstruktur, dan lebih efektif. Ini bukan sekadar aplikasi — ini adalah jembatan yang memperkuat kerjasama demi tumbuh kembang anak yang lebih baik.",
    ],
  },
  {
    slug: "peran-teknologi-memantau-tumbuh-kembang-anak",
    title: "Peran Teknologi dalam Memantau Tumbuh Kembang Anak",
    description: "Teknologi bisa menjadi alat bantu yang efektif untuk memantau perkembangan anak. Simak bagaimana cara bijak memanfaatkannya di artikel ini.",
    date: "2026-07-16",
    author: "Tim CDPS",
    category: "Edukasi",
    readTime: "5 menit",
    image: "/blog/placeholder.svg",
    content: [
      "Di era digital ini, teknologi bukan lagi sekadar alat hiburan, tetapi juga dapat menjadi mitra yang efektif dalam mendidik dan memantau tumbuh kembang anak. Banyak orang tua dan guru mulai memanfaatkan aplikasi dan platform digital untuk mendukung proses pembelajaran dan pengasuhan. Lantas, bagaimana sebenarnya peran teknologi dalam memantau tumbuh kembang anak?",
      "## Peran Teknologi dalam Pendidikan Anak Usia Dini",
      "### 1. Memudahkan Dokumentasi dan Pemantauan",
      "Dulu, mencatat perkembangan anak dilakukan manual di buku catatan. Sekarang, platform seperti CDPS memungkinkan guru mendokumentasikan daily report, portofolio, dan laporan perkembangan secara digital. Orang tua bisa memantau perkembangan anak secara real-time dari smartphone mereka. Tidak perlu lagi menunggu rapat akhir semester untuk mengetahui bagaimana perkembangan anak di sekolah.",
      "### 2. Memperkuat Komunikasi Sekolah dan Orang Tua",
      "Teknologi menjembatani komunikasi antara guru dan orang tua yang sering terkendala waktu. Dengan fitur notifikasi otomatis, orang tua langsung mendapat informasi begitu guru mengupdate laporan. Ini memastikan tidak ada informasi penting yang terlewat.",
      "### 3. Efisiensi Administrasi Sekolah",
      "Teknologi membantu guru dalam administrasi — absensi digital, catatan harian, hingga laporan triwulan bisa dikerjakan lebih cepat. Waktu guru jadi lebih efisien sehingga bisa fokus mendampingi anak. Sekolah pun memiliki data yang rapi dan mudah diakses kapan saja.",
      "## Tips Menggunakan Teknologi dengan Bijak",
      "Meskipun teknologi menawarkan banyak kemudahan, ada beberapa hal yang perlu diperhatikan:",
      "### Pilih Platform yang Tepat dan Aman",
      "Tidak semua platform digital aman untuk data anak. Pastikan memilih platform yang memiliki sistem keamanan berlapis dan enkripsi data. CDPS mengutamakan keamanan data dengan akses terbatas dan perlindungan privasi penuh.",
      "### Jadikan Teknologi sebagai Pelengkap, Bukan Pengganti",
      "Peran orang tua dan guru tetap yang utama. Teknologi hanyalah alat bantu. Jadwalkan juga interaksi langsung antara anak dengan orang tua dan guru. Gunakan data dari aplikasi sebagai bahan diskusi, bukan sebagai pengganti obrolan hangat dengan anak.",
      "### Batasi Penggunaan Gadget untuk Anak",
      "Meskipun aplikasi edukatif bermanfaat, Screen time anak usia dini sebaiknya tetap dibatasi. World Health Organization (WHO) merekomendasikan tidak lebih dari 1 jam per hari untuk anak usia 2-4 tahun. Pastikan teknologi digunakan secara interaktif bersama orang dewasa, bukan sebagai baby sitter digital.",
      "## Kesimpulan",
      "Teknologi memiliki peran yang semakin penting dalam dunia pendidikan anak usia dini. Dari daily report hingga portofolio digital, semua bisa diakses dengan mudah melalui platform seperti CDPS. Namun, teknologi harus digunakan dengan bijak — sebagai alat bantu, bukan pengganti peran orang tua dan guru. Dengan pendekatan yang tepat, teknologi bisa menjadi mitra terbaik untuk memantau dan mendukung tumbuh kembang anak.",
    ],
  },
  {
    slug: "5-aktivitas-stimulasi-perkembangan-anak-di-rumah",
    title: "5 Aktivitas Seru untuk Stimulasi Perkembangan Anak di Rumah",
    description: "Stimulasi perkembangan anak tidak harus mahal. Ini 5 aktivitas sederhana dan seru yang bisa dilakukan di rumah menggunakan barang sehari-hari.",
    date: "2026-07-13",
    author: "Tim CDPS",
    category: "Tips Parenting",
    readTime: "6 menit",
    image: "/blog/placeholder.svg",
    content: [
      "Stimulasi perkembangan anak usia dini bisa dilakukan dengan aktivitas sederhana menggunakan barang yang sudah ada di rumah. Tidak perlu mainan mahal atau alat khusus — yang paling penting adalah kebersamaan dan kreativitas orang tua. Artikel ini akan membahas 5 aktivitas seru yang efektif untuk menstimulasi tumbuh kembang anak di rumah.",
      "## Mengapa Stimulasi Penting untuk Tumbuh Kembang Anak?",
      "Pada usia 0-6 tahun, otak anak berkembang sangat pesat — 80% perkembangan otak terjadi di periode ini. Stimulasi yang tepat akan membantu anak mengembangkan kemampuan kognitif, motorik, bahasa, dan sosial-emosional secara optimal. Semakin bervariasi stimulasi yang diberikan, semakin banyak koneksi saraf (sinaps) yang terbentuk di otak anak.",
      "## 5 Aktivitas Stimulasi yang Bisa Dilakukan di Rumah",
      "### 1. Bermain Pasir atau Beras",
      "Siapkan wadah besar berisi beras, pasir mainan, atau biji-bijian. Beri anak sendok, gelas plastik, corong, dan mainan kecil. Biarkan anak menuang, memindahkan, dan menyendok isi wadah. Aktivitas ini melatih motorik halus dan sensorik anak. Anak belajar tentang tekstur, volume, dan koordinasi tangan-mata.",
      "Cara melakukannya: gelar terpal atau koran bekas di lantai agar mudah dibersihkan, lalu biarkan anak bereksplorasi dengan pengawasan. Aktivitas ini sangat seru dan bisa membuat anak fokus selama 30-60 menit.",
      "### 2. Membaca Buku Bergambar",
      "Luangkan 15-20 menit setiap hari untuk membaca bersama anak. Pilih buku dengan ilustrasi besar dan warna-warni. Tunjuk gambar, tanyakan pendapat anak, dan buat cerita jadi interaktif. Misalnya, \"Menurut adik, kucing itu sedang apa ya?\" atau \"Warnanya apa itu?\".",
      "Membaca bersama tidak hanya mengembangkan kemampuan bahasa dan literasi, tetapi juga memperkuat ikatan emosional antara orang tua dan anak. Jadikan aktivitas membaca sebagai rutinitas yang menyenangkan, bukan kewajiban.",
      "### 3. Bermain Peran (Role Play)",
      "Ajak anak berpura-pura menjadi tokoh tertentu — koki, dokter, penjual, atau super hero. Sediakan alat peraga sederhana seperti topi, celemek, atau alat mainan. Bermain peran mengembangkan imajinasi, keterampilan sosial, empati, dan kemampuan bahasa anak.",
      "Anda bisa memulai dengan tema yang familiar bagi anak. Misalnya bermain jualan makanan menggunakan mainan atau potongan kertas sebagai uang. Biarkan anak memimpin permainan dan Anda mengikuti alurnya.",
      "### 4. Melukis dan Menggambar",
      "Sediakan kertas, crayon, cat air, atau pensil warna. Biarkan anak mengekspresikan dirinya melalui gambar. Jangan khawatir soal hasil akhir atau kekurangan — fokuslah pada prosesnya. Tanyakan tentang gambar yang dibuat: \"Wah, ini gambar apa, Nak?\" atau \"Ceritakan dong tentang gambarnya.\"",
      "Aktivitas melukis melatih motorik halus, kreativitas, dan kemampuan berekspresi. Selain itu, hasil karya anak bisa dikumpulkan di portofolio digital CDPS sebagai dokumentasi perkembangan kreativitas si kecil.",
      "### 5. Berjalan-jalan di Alam",
      "Ajak anak ke taman, halaman rumah, atau area terbuka hijau. Amati dedaunan, bunga, serangga, dan awan. Tanyakan apa yang mereka lihat, dengar, dan rasakan. Aktivitas luar ruangan ini baik untuk perkembangan fisik (olahraga ringan) dan kognitif (observasi dan rasa ingin tahu).",
      "Anda bisa membuat permainan sederhana seperti \"siapa yang bisa menemukan daun paling besar\" atau \"kumpulkan 5 batu kecil dengan warna berbeda\". Ini membuat jalan-jalan lebih interaktif dan seru.",
      "## Tips Agar Aktivitas Stimulasi Lebih Efektif",
      "Yang terpenting dari semua aktivitas di atas bukanlah mainan atau alatnya, melainkan kehadiran dan perhatian penuh orang tua. Matikan TV, jauhkan smartphone, dan fokuslah pada momen bersama anak. Jadwalkan waktu khusus setiap hari untuk bermain dan belajar bersama.",
      "Catat momen-momen berharga ini di portofolio digital CDPS. Foto hasil karya anak, rekam video saat mereka sedang asyik bermain, dan simpan semua dokumentasi sebagai kenangan dan bukti tumbuh kembang mereka.",
    ],
  },
];

export const blogCategories = [...new Set(blogPosts.map((p) => p.category))];
